### ISSUE TITLE
Direct trade.

### ISSUE THREAD

**Issue by ShilohBeeler** [ShilohBeeler/discordRPG#23]
Trade will become more complex, with .trade open [player1] initializing a trade, each person being able to do .trade summary to see a list of who gets what, and .trade add [item] and .trade remove [item]. .trade confirm locks trade, and the other person can then .trade confirm or .trade cancel.

_Subcommands_: 
.trade open [player]
.trade accept
.trade reject
.trade add [item] [number]
.trade remove [item] [number]
.trade summary
.trade confirm
.trade cancel

**Comment by Shymain** [comment]
JSON File format:
{
    trades:{
        userid:{
            recipient:"userid",
            user1:"name",
            user1_inventory:{
                "iron_ore":3,
                "oak_wood":5,
                "health_potion":1
            },
            user2:"name",
            user2_inventory:{
                "coins":50,
                "steel_ore":1
            },
            trade_close:false
        }
    }
}

**Comment by ShilohBeeler** [comment]
JSON Example: http://hastebin.com/wipotutivi.sm

On .trade open, a generic file with sender and recipient's userids and name will be created. The recipient's id will then be inserted as a key in a hashmap with the sender's id as the value. Only .trade accept and .trade reject will be possible, as trade_accept will be false. On .trade accept, that value is set to true, and .trade add, remove, summary, and confirm are possible. At any point, .trade cancel can be enacted by either party to cancel the part. You can not open, accept or reject a trade if you are already in one.

.trade add [item] [number] will add the items to that player's trade inventory, and remove it from actual inventory. .trade remove [item] [number] removes said item from trade inventory, and adds it to actual inventory. .trade cancel does this for all items.

.trade confirm locks down trade_close, and only allows .trade confirm and .trade cancel to be used. The user who confirmed first does has their ID inserted into first_close to prevent abuse. Once both players have confirmed, user1_inventory is transferred to the inventory of player 2, and user2_inventory is transferred to the inventory of player 1. The JSON object is deleted, and the hashmap entry is removed.

**Comment by ShilohBeeler** [comment]
COMPLETE! Every single feature here is implemented!
